### ISSUE TITLE
Very strict type checking for *

### ISSUE THREAD

**Issue by gabrielgellner** [timholy/AffineTransforms.jl#13]
If I have something like
```jl
a = [1.0 2.0; 3.0 4.0]
tformrotate(\pi/2) * a[1, :]'
```
gives a method error since the code for `*` checks for an `AbstractVector` not a compatibly shaped `AbstractArray`

Happy to send a pull request to add methods for `AbstractArray` if the error is not intentional.

**Comment by timholy** [comment]
I'd be happy to accept a PR to change it. You can also say `vec(a[1, :])` and it will make it a vector.

**Comment by gabrielgellner** [comment]
Yeah easy enough to get around, but seems unnecessarily cruel to poor slices ;)
I notice that the `tformfwd!` requires a `AbstractVecOrMat`, should the `*` methods signature be changed to that? Or would you prefer a separate definition? If you send in incompatible shaped array to `tformfwd` it gives a meaningful error (from `A_mul_B!`).

**Comment by timholy** [comment]
> seems unnecessarily cruel to poor slices ;)

In julia-0.5 `a[1,:]` will give you a vector back, so it's not cruel for long :smile:

Yes, I'd be fine with having the signature of the `*` methods changed.

**Comment by gabrielgellner** [comment]
So happy the dimension dropping got in! Is this worth worrying about then? If so I will get the pull request asap.
