### ISSUE TITLE
Does piecewise affine transformation belong to this module?

### ISSUE THREAD

**Issue by dfdx** [timholy/AffineTransforms.jl#2]
I have some code for performing piecewise affine transformation on an image. In short, it allows doing things like this:

![pwa](https://cloud.githubusercontent.com/assets/428171/7220076/18f67a08-e6c4-11e4-90d5-ce9fcc0840cf.png)

It takes some image, source and destination shape (set of points), triangulates each shape and warps every triangle from source to destination. On the image above left face is transformed from its original shape to the shape of the face in the middle, and result is shown on the right image. So in code it looks something like this: 

    pa_warp(img, src_shape, dst_shape)

Which is pretty different from what you have in this repository for normal affine transformation. 

So I'm wondering, should I contribute code for PWA to this repository or better create new one? In your opinion, what will be less confusing for users?

**Comment by timholy** [comment]
First and foremost, I really like the functionality!

With regards to where it should live: I could imagine it going anywhere, but on balance I wonder if it's better in its own repository. We might want to have an `ImageDeformations` repository, or something? But I'd also be very pleased to have it here, and would begin by giving you push privileges if that's what you want to do.

Alternatively, if you think the name I've adopted for this package is too grandiose given the limited functionality it provides, feel free to share how you think things should be structured.

**Comment by dfdx** [comment]
`ImageDeformations` would be really cool! Though, I believe we need to collect some more algorithms to start such a package. So for now I will stay with separate repository, and later we can merge (or even simply import) all efforts into a single package. 

I'm closing this issue and will come up with a new package in a couple of days.
